# Generated by Django 5.0.6 on 2025-05-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_data_loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('main_attribute', models.CharField(choices=[('hero_strength', 'Strength'), ('hero_agility', 'Agility'), ('hero_intelligence', 'Intelligence'), ('hero_universal', 'Universal')], max_length=100)),
                ('complexity', models.PositiveSmallIntegerField()),
                ('advice', models.JSONField()),
                ('history', models.JSONField()),
                ('attack', models.JSONField()),
                ('defense', models.JSONField()),
                ('mobility', models.JSONField()),
                ('hp', models.JSONField()),
                ('mp', models.JSONField()),
                ('attributes', models.JSONField()),
                ('attack_type', models.CharField(choices=[('hero_attack_type_melee', 'melee'), ('hero_attack_type_ranged', 'ranged')], max_length=100)),
                ('talents', models.JSONField()),
                ('description', models.JSONField()),
                ('video', models.CharField(blank=True, max_length=2222, null=True)),
                ('image', models.CharField(blank=True, max_length=2222, null=True)),
                ('icon', models.CharField(blank=True, max_length=2222, null=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='LanguagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('attributes_img', models.JSONField(default={'hero_agility': 'hero_agility.png', 'hero_intelligence': 'hero_intelligence.png', 'hero_strength': 'hero_strength.png', 'hero_universal': 'hero_universal.png'})),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('content', models.JSONField()),
                ('date', models.JSONField()),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Aspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=2222, null=True)),
                ('ability_description', models.JSONField(blank=True, null=True)),
                ('ability_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_icon', models.CharField(blank=True, max_length=2222, null=True)),
                ('full_description', models.JSONField(blank=True, null=True)),
                ('facet_bonuses', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hero')),
            ],
            options={
                'verbose_name': 'Aspect',
                'verbose_name_plural': 'Aspects',
            },
        ),
        migrations.CreateModel(
            name='HeroRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hero_carry', 'Carry'), ('hero_support', 'Support'), ('hero_nuker', 'Nuker'), ('hero_disabler', 'Disabler'), ('hero_jungler', 'Jungler'), ('hero_durable', 'Durable'), ('hero_escape', 'Escape'), ('hero_pusher', 'Pusher'), ('hero_initiator', 'Initiator')], max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hero')),
            ],
            options={
                'verbose_name': 'Hero role',
                'verbose_name_plural': 'Hero roles',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField()),
                ('icon', models.CharField(blank=True, max_length=2222, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.JSONField()),
                ('cooldown', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(max_length=100)),
                ('spell_effects', models.JSONField()),
                ('video', models.CharField(blank=True, max_length=2222, null=True)),
                ('tip', models.JSONField(blank=True, null=True)),
                ('is_innate', models.BooleanField(default=False)),
                ('ability_is_granted_by_shard', models.BooleanField(default=False)),
                ('ability_is_granted_by_scepter', models.BooleanField(default=False)),
                ('ability_has_scepter', models.BooleanField(default=False)),
                ('ability_has_shard', models.BooleanField(default=False)),
                ('scepter_description', models.JSONField(blank=True, null=True)),
                ('shard_description', models.JSONField(blank=True, null=True)),
                ('aghs_icon', models.CharField(blank=True, max_length=2222, null=True)),
                ('is_facet', models.BooleanField(default=False)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hero')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
