# Generated by Django 5.0.6 on 2025-05-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name_url',
            field=models.CharField(blank=True, max_length=2222, null=True),
        ),
    ]
