# Generated by Django 5.0.6 on 2025-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hero_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
